# Generated by Django 5.1.2 on 2024-11-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile/profile.png', upload_to='users/profile'),
        ),
    ]
